---
name: Deploy Apps 🚀

on:
  push:
  workflow_dispatch:

env:
  SHINYAPPSIO_ACCOUNT: vedha-viyash
  APP_PREFIX: NEST
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: rocker/shiny
    strategy:
      fail-fast: false
      matrix:
        directory: ["simple-shiny"]
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Restore renv from cache
        uses: actions/cache@v2
        env:
          CACHE_KEY: renv-${{ runner.arch }}-${{ runner.os }}-${{ env.R_VERSION }}-${{ matrix.directory }}-${{ matrix.channel }}
        with:
          path: ${{ github.event.repository.name }}/${{ matrix.directory }}/renv/library
          key: ${{ env.CACHE_KEY }}-${{ hashFiles(format('{0}/{1}/renv.lock', github.event.repository.name, matrix.directory)) }}
          restore-keys: ${{ env.CACHE_KEY }}-

      - name: Install R packages using renv and update the renv snapshot
        shell: Rscript {0}
        working-directory: ${{ github.event.repository.name }}/${{ matrix.directory }}
        run: |
          options(renv.config.cache.symlinks = FALSE)
          renv::restore(clean = TRUE)

      - name: Print the new renv.lock file for ${{ matrix.directory }}
        working-directory: ${{ github.event.repository.name }}/${{ matrix.directory }}
        run: cat renv.lock
