---
name: Deploy Apps 🚀
on: push
permissions:
  contents: read
env:
  SHINYAPPSIO_ACCOUNT: vedha-viyash
jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: rocker/shiny
    strategy:
      fail-fast: false
      matrix:
        directory: ["basic-teal"]
        channel: ["stable"]
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup npm packages
        if: steps.find-cypress.outputs.has-cypress-tests == 'true'
        working-directory: ${{ matrix.directory }}/js
        run: |
          npm i --save-dev
          ln -s node_modules ../tests/node_modules

      - name: Front end test to check if the app works fine
        if: steps.find-cypress.outputs.has-cypress-tests == 'true'
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          working-directory: ${{ matrix.directory }}/js
          start: npm run run-app
          wait-on: "http://localhost:3333"
          wait-on-timeout: 500
          project: ../tests
