---
name: Deploy Apps 🚀

on:
  push:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SHINYAPPSIO_ACCOUNT: genentech
  APP_PREFIX: NEST

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    if: >
      !contains(github.event.commits[0].message, '[skip deploy]')
    strategy:
      fail-fast: false
      matrix:
        repository:
          [
            "https://insightsengineering.r-universe.dev",
            "https://pharmaverse.r-universe.dev",
          ]
    steps:
      - name: Set APP_SUFFIX
        run: |
          if [ "${{ matrix.repository }}" = "https://insightsengineering.r-universe.dev" ]; then
            echo "APP_SUFFIX=release" >> $GITHUB_ENV
          else
            echo "APP_SUFFIX=main" >> $GITHUB_ENV
          fi

      - name: Commit updated renv.lock file
        if: ${{ steps.set_app_suffix.outputs.APP_SUFFIX == 'main' }}
        run: |
          echo "Yes"
