---
name: Deploy Apps 🚀

on:
  push:
  workflow_dispatch:

env:
  SHINYAPPSIO_ACCOUNT: vedha-viyash
  APP_PREFIX: NEST
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: Rscript {0}
        run: |
          print("${{ env.GITHUB_PAT }}")
          Sys.getenv("GITHUB_PAT")
