name: Commit test
on: push
permissions:
  contents: write
jobs:
  main:
    name: Restore renv from cache
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    strategy:
      fail-fast: false
      matrix:
        directory: ["simple-shiny"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create a file
        shell: bash
        run: |
          echo "Something" >> test.txt

      - name: Commit updated renv.lock file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "[bot] test commit"
          file_pattern: "test.txt"
          commit_user_name: test-bot
