name: Commit test
on: push
permissions:
  contents: write

jobs:
  create_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create and commit file
        run: |
          echo "Something" > test.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test.txt
          git commit -m "Add test.txt file"
          git push origin main
