---
name: Deploy Apps 🚀
on: push
permissions:
  contents: read
env:
  SHINYAPPSIO_ACCOUNT: vedha-viyash
jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: rocker/shiny
    strategy:
      fail-fast: false
      matrix:
        directory: ["basic-teal"]
        channel: ["stable"]
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3

      - name: Setup system dependencies for cypress and python app
        run: >
          apt-get update && apt-get install --yes
          libgtk2.0-0 libgbm-dev libnotify-dev libgconf-2-4 xvfb python3.10-venv libnss3 libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup npm packages
        working-directory: ${{ matrix.directory }}/js
        run: |
          npm i --save-dev
          ln -s node_modules ../tests/node_modules

      - name: Front end test to check if the app works fine
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          working-directory: ${{ matrix.directory }}/js
          start: npm run run-cypress
          wait-on: "http://localhost:3333"
          wait-on-timeout: 500
          project: ../tests
