name: Restore renv from cache
on: push
permissions:
  contents: read
jobs:
  main:
    name: Restore renv from cache
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    strategy:
      fail-fast: false
      matrix:
        directory: ["simple-shiny"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Inspect contents of the renv library before cache
        shell: bash
        run: |
          ls ${{ matrix.directory }}/renv/library

      - name: Restore renv from cache
        uses: actions/cache@v2
        env:
          CACHE_KEY: renv-${{ runner.arch }}-${{ runner.os }}-${{ matrix.directory }}
        with:
          path: ${{ matrix.directory }}/renv/library
          key: ${{ env.CACHE_KEY }}-${{ hashFiles(format('{0}/renv.lock', matrix.directory)) }}
          restore-keys: ${{ env.CACHE_KEY }}-

      - name: Inspect contents of the renv library after cache
        shell: bash
        run: |
          ls ${{ matrix.directory }}/renv/library

      - name: Sync renv with lockfile
        shell: Rscript {0}
        working-directory: ${{ matrix.directory }}
        run: |
          options(renv.config.cache.symlinks = FALSE)
          renv::restore(clean = TRUE)
